apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
spec:
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
        - name: fehszo-server
          image: peszog/fehszo-server:{{ .Values.env.APP_VERSION }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

        - name: kafka-broker
          image: bashj79/kafka-kraft
          ports:
            - containerPort: 9092
              name: kafka-broker
          command: ["/bin/sh", "-c"]
          args:
            - "sleep infinity"
          env:
            - name: KAFKA_BROKER_HOST
              value: kafka-broker
            - name: KAFKA_BROKER_PORT
              value: "9092"

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
      fsGroup: 2000
