apiVersion: v1
kind: Service
metadata:
  name: argo-app
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9092
      targetPort: kafka
      protocol: TCP
      name: kafka
  selector:
    app: argo-app