name: actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
  IMAGE_NAME: argo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine if Docker build is necessary
        id: check_changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^app/' || echo "::set-output name=build_needed::false"

      - name: Login to Docker Hub
        if: steps.check_changes.outputs.build_needed != 'false'
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        if: steps.check_changes.outputs.build_needed != 'false'
        run: cd ./app && docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        if: steps.check_changes.outputs.build_needed != 'false'
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        if: steps.check_changes.outputs.build_needed != 'false'
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
