name: actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
  IMAGE_NAME: fehszo-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Determine if Docker build is necessary
        id: check_changes
        shell: pwsh
        run: |
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^app/'}
          $HasDiff = $SourceDiff.Length -gt 0
          
          Write-Output "docs_changed=$HasDiff" >> $GITHUB_ENV

          echo "=============================="
          echo "Files changed: $HasDiff"

          echo "${{ env.DOCS_CHANGED }}"

      - name: Login to Docker Hub t
        if: ${{ steps.check_changes.outputs.docs_changed == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Login to Docker Hub T
        if: ${{ steps.check_changes.outputs.docs_changed == 'True' }}
        run: |
          echo "Login to Docker Hub T: ${{ steps.check_changes.outputs.docs_changed }}"

      - name: Login to Docker Hub f
        if: ${{ steps.check_changes.outputs.docs_changed == 'false' }}
        run: |
          echo "Login to Docker Hub f: ${{ steps.check_changes.outputs.docs_changed }}"

      - name: Login to Docker Hub F
        if: ${{ steps.check_changes.outputs.docs_changed == 'False' }}
        run: |
          echo "Login to Docker Hub F: ${{ steps.check_changes.outputs.docs_changed }}"
          
      - name: Build Docker image
        if: ${{ env.DOCS_CHANGED == 'True' }}
        run: |
          echo "The saved value is: ${{ steps.check_changes.outputs.docs_changed }}"
          cd ./app && docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        if: steps.check_changes.outputs.docs_changed == 'True'
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        if: steps.check_changes.outputs.docs_changed == 'True'
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
