name: actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
  IMAGE_NAME: fehszo-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Determine if Docker build is necessary
        id: check_changes
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under app/ has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^app/'}
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docs_changed"
          $echo "{docs_changed}={$HasDiff}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: ${{ steps.check_changes.outputs.docs_changed }} == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        if: ${{ steps.check_changes.outputs.docs_changed }} == 'true'
        run: cd ./app && docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        if: ${{ steps.check_changes.outputs.docs_changed }} == 'true'
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        if: ${{ steps.check_changes.outputs.docs_changed }} == 'true'
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
